### ISSUE TITLE
Package does not install on Python 3.9

### ISSUE THREAD

**Issue by joshschmelzle** [Mywayking/openstreetmap#1]
Hi, I hope you are well. I am unable to install and use your project with Python 3.9 on Windows 10.

Unable to install from PyPI:

```
C:\Users\joshu\repos\openstreetmap>python -m pip install openstreetmap
Collecting openstreetmap
  Using cached openstreetmap-0.0.17.tar.gz (8.0 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\joshu\AppData\Local\Programs\Python\Python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\joshu\\AppData\\Local\\Temp\\pip-install-p8jciogv\\openstreetmap_08fcddcb5e634d1db933c520d52557fd\\setup.py'"'"'; __file__='"'"'C:\\Users\\joshu\\AppData\\Local\\Temp\\pip-install-p8jciogv\\openstreetmap_08fcddcb5e634d1db933c520d52557fd\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\joshu\AppData\Local\Temp\pip-pip-egg-info-oud791iu'
         cwd: C:\Users\joshu\AppData\Local\Temp\pip-install-p8jciogv\openstreetmap_08fcddcb5e634d1db933c520d52557fd\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\joshu\AppData\Local\Temp\pip-install-p8jciogv\openstreetmap_08fcddcb5e634d1db933c520d52557fd\setup.py", line 8, in <module>
        with open("README.md", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Unable to install from repo:

```
C:\Users\joshu\repos\openstreetmap>python -m pip install .
Processing c:\users\joshu\repos\openstreetmap
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\joshu\AppData\Local\Programs\Python\Python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\joshu\\AppData\\Local\\Temp\\pip-req-build-rgz3xaci\\setup.py'"'"'; __file__='"'"'C:\\Users\\joshu\\AppData\\Local\\Temp\\pip-req-build-rgz3xaci\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\joshu\AppData\Local\Temp\pip-pip-egg-info-dvmb5bsz'
         cwd: C:\Users\joshu\AppData\Local\Temp\pip-req-build-rgz3xaci\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\joshu\AppData\Local\Temp\pip-req-build-rgz3xaci\setup.py", line 9, in <module>
        long_description = fh.read()
      File "C:\Users\joshu\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 420: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Mywayking** [comment]
already fix it ,try again

**Comment by joshschmelzle** [comment]
Confirmed! Thank you!

```
C:\Users\joshu\repos\openstreetmap>python -m pip install openstreetmap
Collecting openstreetmap
  Downloading openstreetmap-0.0.19.tar.gz (7.3 kB)
Requirement already satisfied: lxml in c:\users\joshu\appdata\local\programs\python\python39\lib\site-packages (from openstreetmap) (4.6.2)
Requirement already satisfied: requests in c:\users\joshu\appdata\local\programs\python\python39\lib\site-packages (from openstreetmap) (2.24.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\joshu\appdata\local\programs\python\python39\lib\site-packages (from requests->openstreetmap) (2020.12.5)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\joshu\appdata\local\programs\python\python39\lib\site-packages (from requests->openstreetmap) (1.25.11)
Requirement already satisfied: idna<3,>=2.5 in c:\users\joshu\appdata\local\programs\python\python39\lib\site-packages (from requests->openstreetmap) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\joshu\appdata\local\programs\python\python39\lib\site-packages (from requests->openstreetmap) (3.0.4)
Using legacy 'setup.py install' for openstreetmap, since package 'wheel' is not installed.
Installing collected packages: openstreetmap
    Running setup.py install for openstreetmap ... done
Successfully installed openstreetmap-0.0.19

C:\Users\joshu\repos\openstreetmap>python -V
Python 3.9.0

C:\Users\joshu\repos\openstreetmap>ver

Microsoft Windows [Version 10.0.19042.685]
```
